### ISSUE TITLE
Interface aplikasi Konversi satuan

### ISSUE THREAD

**Issue by nurkholilahhrp** [iqballm09/project-team-dta#1]
![massa](https://user-images.githubusercontent.com/89146841/130357622-eed922ea-4e16-4439-9851-a26bfa58f969.jpg)
![suhu](https://user-images.githubusercontent.com/89146841/130357693-97d38b34-22dd-4bbe-9ade-7c262290b9fb.jpg)
![decimal](https://user-images.githubusercontent.com/89146841/130357709-3fc8f643-8929-4404-9a0f-cf3991469014.jpg)
![data](https://user-images.githubusercontent.com/89146841/130357717-049cdd1c-e335-4227-807b-a1c905b497a1.jpg)
![luas](https://user-images.githubusercontent.com/89146841/130357722-c18eaf01-6a95-42e7-b31f-b20a97ac0a97.jpg)
![waktu](https://user-images.githubusercontent.com/89146841/130357727-337f490f-e383-4dfb-95f2-54ce5f2758af.jpg)
![panjang](https://user-images.githubusercontent.com/89146841/130357736-23e24f2a-c6a4-4a74-b9a4-b68b811ad1d4.jpg)

**Comment by iqballm09** [comment]
Butuh buat diupdate lg soalnya yg luas ga keburu dibuat
